version: '3'
services:
  service-a:
    restart: always
    build:
      context: ./service-a
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
  service-b:
      restart: always
      build:
        context: ./service-b
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      env_file:
      - ./service-b/.env
  collector:
    restart: always
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector.config.yml:/etc/otel-collector-config.yaml
  zipkin:
    restart: always
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"