version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  webserver:
      build:
        context: .
      ports:
        - "8080:8080"
      depends_on:
        - redis
      volumes:
        - ./cmd/server/configs.db:/app/configs.db
        - ./cmd/server/.env:/app/.env