# Stage 1: Build the application
FROM golang:1.22

# Set the working directory inside the container
WORKDIR /app

# Copy the source code
COPY . .

# Build the Go application with additional flags to reduce binary size
RUN go build -o app

# Set the command to run the executable
ENTRYPOINT ["/app/app"]
